### ISSUE TITLE
missing resource bundle in the provided ecj 3.6.2

### ISSUE THREAD

**Issue by amirkibbar** [t7mp/t7mp#26]
Hi,

in the ecj362-1.0.0.jar that the plugin brings there's a missing messages.properties file, and maybe there are other missing things. I've compared the ecj362-1.0.0.jar with a real tomcat 7.0.16 installation - the real installation brings a jar called ecj-3.6.2.jar and in it the messages.properties exists.

This properties file is a resource bundle loaded by the jsp compiler and it seems that without it it is not possible to compile even the simplest jsps.

hope this can be quickly fixed (I'm using t7 version 0.9.8M1).

thanks,
Amir

**Comment by t7mp** [comment]
Hi Amir,

the problem is, that we could not find the original ecj-3.6.2 in a open maven-repository. So we re-packaged it from the sources to ship it separat.
If you find any other missing pieces in the jar provided by us, let us know please.

When I find the messages.properties that is missing, I will fix it today an make new milestone release.

Cheers
Jörg

**Comment by amirkibbar** [comment]
Perhaps you can take the jar from a standard tomcat installation?

-----Original Message-----

**Comment by t7mp** [comment]
Hi Amir,

I patched the ecj-jar and created a new release (0.9.8.M1A). Should be in maven-central.
If this new version works for you please don't forget to close the issue. So for #25 too.

Cheers
Jörg

**Comment by amirkibbar** [comment]
Hi Jörg,

the new ecj works.

thanks,
Amir
