### ISSUE TITLE
using a jndi resource

### ISSUE THREAD

**Issue by amirkibbar** [t7mp/t7mp#27]
hi,

I'd like to use a jndi resource (a standard jdbc data source) in my war. I know that the tomcatConfigDirectory parameter is supposed to take configuration files from the ${basedir}/src/main/tomcat/conf and use them in the tomcat instance in the target directory. However, it seems that the content of the ${basedir}/src/main/tomcat/conf/Catalina/localhost is not copied to the target directory - so the context xml I put in it is not copied to the target and my jndi resource is not configured correctly.

I have a workaround - I'm copying my context file manually before running t7, however, I think this should be taken care of by the plugin.

thanks,
Amir

**Comment by marcobuss** [comment]
Hi Amir,

i have checkt the code and the default position for configurations is ${basedir}/src/main/tomcat/conf. Try to put the context.xml to this directory.

We use this in nearly all projects and it works great. 
Because we use the plugin only for testing we have put the context.xml in a directory different from the default. For us the configuration resists in ${basedir}/src/test/tomcat/conf and so in our pom the directory is set with the tomcatConfigDirectory property.

**Comment by amirkibbar** [comment]
Hi Marco,

If I put a context.xml in the conf it works just fine, but this forces me to put all the definitions of all the web applications in one context.xml file. I thought it would be possible to define individual contexts under conf/Catalina/localhost just like in a real tomcat.

Thanks,
Amir

-----Original Message-----

**Comment by t7mp** [comment]
Hi Amir,

you should't do something by hand in 'conf/Catalina/whatEverHost'.
Please read the Tomcat-Documentation to JNDI-Resources and the correct usage.
[Here](http://tomcat.apache.org/tomcat-7.0-doc/jndi-resources-howto.html#context.xml_configuration) you can find all you need.

In your case you have to put the context.xml to the 'META-INF'-directory.

**Comment by amirkibbar** [comment]
Well, looks like I've been doing it wrong for years... how silly of me!

-----Original Message-----
