### ISSUE TITLE
can I add war file?

### ISSUE THREAD

**Issue by ishara** [t7mp/t7mp#54]
I have list of wars that are already build  . Can I deploy those wars ?

Thank you

**Comment by marcobuss** [comment]
Sorry i don´t understand that issue.

Where du you want to deploy? A war File to an stand alone Tomcat? If this is what you mean this plugin is not suiteable for you.
If you want to deploy a war to a repository this plugin is also not suitable for you.

**Comment by ishara** [comment]
I want to deploy local webapp for debugging . the war files are already build with ant build .

I have got the solution for this using 'mvn install:install' install local repository and then it can take as webappArtifact.

Any other solution?

Thank for your reply.

**Comment by jbellmann** [comment]
Hi Ishara,

if you have the '.war'-artifacts installed in your local maven-repository or any other available maven-repository it is possible to define that artifacts as applications in tomcat. As documented [here](http://t7mp.github.com/docu/html/ch01.html#d4e25) define all needed '.war'-artifacts as a 'webappArtifact' and configure a 'contextPath', otherwise the 'artifactId' would be taken as the 'contextPath'. Since the last release '0.9.10.M3' it should be possible to define an 'systemPath' if you don't have installed your '.war'-artifacts in a local maven-repository or any other. Please have a look to #53.

Cheers
Jörg

**Comment by jbellmann** [comment]
Hi Ishara,

please let us know if the comments where helpful or when you have further questions. Please close the isssues you openened. We can better sleep then. ;-)

Cheers
Jörg
