### ISSUE TITLE
how can I hot deploy ?

### ISSUE THREAD

**Issue by ishara** [t7mp/t7mp#56]
My current wars install to local repository and t7:run working fine . How can I do the hot deploy? . 
I have many war files and it will take some time to deploy all . 
How can can I deploy one war from local repository when tomcat is already running ? 

Thank You.

**Comment by jbellmann** [comment]
Hi Ishara,

interesting requirements ;-). But I think that is out of scope for this plugin. It was developed mainly for testing /integration-testing in the build-cycle of maven. But before I say this is impossible I have some questions:
- how many wars do you want to deploy? what is the average startup-time for one war-file?
- do you want to hot-deploy regularly? Maybe when war-file X was installed in local repository? How would you trigger that event? Or only sometimes, when you see that war-file Y has an easy to fix error and because it needs longer to restart the tomcat with all war-files then to fix the broken war-file Y?
- are there any dependencies between the war-files? Is there a strict ordering to start the war-files?
- do you have any experiences with hot-deployment of your war-files? Excessive redeployments can lead to OOME (OutOfMemoryException) on tomcat (and any other container)? Have you tested that before?

Cheers
Jörg

**Comment by ishara** [comment]
Hi Jörg
- I have around 30+ wars and WebServices modules with DB query on module init, one module  take 5-10 seconds.
- Yes, see below
- No dependencies between wars, No specific order needed. 
- Yes we have doing hot deployment regularly.

I think we can achieve this , When new war file install in local repository If tomcat instance is running that war should copy to webapp.  

Please advice .
Thank you 
Ishara

**Comment by jbellmann** [comment]
Hi Ishara,

that's a lot of wars.
What can we do? Well I think we could use a FilesystemWatcher for this feature that scans the local repository for deployed wars and when it finds any changes copy the war-file to the weapps folder. What do you think about that?

Cheers
Jörg

**Comment by ishara** [comment]
Hi  Jörg

Actually my situation I know the war file change time, we build the war with our own ant task. better to have maven goal copy specific WebArtifact to webapp.

Like mvn t7:hot:WebArtifact
Thank you
Ishara

**Comment by jbellmann** [comment]
Hi,

why don't you specify an simple ant-copy-task to the 'webapps'-folder ? Then you have to build your war with ant and it deploys (per copy) to tomcat if packaging were successful.

Cheers
Jörg

**Comment by jbellmann** [comment]
Maybe my last answers was the point or maybe not. I close this issue because Ishara does not react on my question. Feel free to reopen it when there are some questions again.
