### ISSUE TITLE
Support recent versions of Tomcat 7

### ISSUE THREAD

**Issue by sparhomenko** [t7mp/t7mp#74]
Trying to use t7mp with recent versions of Tomcat 7 (7.0.41, 7.0.41, 7.0.42) fails with "Could not resolve artifact with coordinates com.googlecode.t7mp:tomcat:zip:7.0.4*".

**Comment by jbellmann** [comment]
A new release (0.9.14) is out now. Should be available in maven-central tomorrow (maybe earlier).

Please try it and give some feedback.

Cheers
Jörg

**Comment by sparhomenko** [comment]
Tried out 0.9.14. It is now downloading Tomcat artifact from a different groupId (org.apache.tomcat) and is working properly for me with the recent versions of Tomcat. Closing the issue. Thanks!

**Comment by jbellmann** [comment]
Hi Sergey,

that's right. Earlier versions of tomcat (groupId: com.googlecode.t7mp) where bundled by me. Since version 7.0.35 the Apache-Tomcat-Project deploys full zip and tar.gz. artifacts to maven-central too.

So, one thing I don't have to care about anymore --> more time for the plugin itself ;-)

Cheers.
